[cmob-1311]/Feature/basic design/
giorgimurgulia-space/ChatApp pull request #1
Opened 2023-04-21 09:17 UTC by giorgimurgulia-space

https://spaceneobank.atlassian.net/browse/CMOB-1311

2023-04-21 10:47 UTC, iTarley requested changes

2023-04-21 10:47 UTC, iTarley commented on app/src/main/java/com/insurance/chatapp/BottomUserFragment.kt
ამ ფრაგმენტით არღვევ დავალების ერთ-ერთ პირობას "ფრაგმენტების შექმნისას გაითვალისწინეთ ოოპ-ის ინჰერიტენსის პრინციპი", Base დაგჭირდება

2023-04-21 10:47 UTC, iTarley commented on app/src/main/java/com/insurance/chatapp/BottomUserFragment.kt
როცა იყენებ binding ფრაგმენტში არ დაგავიწდეს 
`override fun onDestroyView() {
    super.onDestroyView()
    _binding = null
}`
https://developer.android.com/topic/libraries/view-binding

2023-04-21 10:47 UTC, iTarley commented on app/src/main/java/com/insurance/chatapp/TopUserFragment.kt
იგივე რაც bottomFragment-ზე დაგიწერე

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/drawable/ic_moon_icon.xml
ic ისედაც icons ნიშნავს, ბოლოში "icon" შეგიძლია წაშალო

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/drawable/ic_send_icon.xml
same

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/drawable/ic_sun_icon.xml
here too

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout-land/activity_main.xml
> +        android:layout_width="6dp"
dimen_6dp

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/activity_main.xml
> +        app:track="@drawable/selector_switch_track"/>
ვერტიკალში გაქვს switchCompat ი და ხორიზონტალში არა, წაშალე აქ ან იქ დაამატე

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/fragment_bottom_user.xml
> +        android:layout_marginBottom="18dp"
dimen_18dp

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/fragment_bottom_user.xml
> +            android:scrollbarTrackVertical="@drawable/shape_scrollbar_track_vertical"
ეს ორი სტილში შეგიძლია გაიტანო

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/fragment_bottom_user.xml
> +            android:layout_height="32dp"
dimen_32dp

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/fragment_top_user.xml
> +        android:layout_marginBottom="18dp"
dimen_18dp

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/fragment_top_user.xml
> +            android:scrollbarTrackVertical="@drawable/shape_scrollbar_track_vertical"
same

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/fragment_top_user.xml
> +            android:layout_height="32dp"
same

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/layout_receive_message.xml
> +        android:layout_marginStart="13dp"
dimen_13dp

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/layout_receive_message.xml
> +        android:layout_marginTop="-13dp"
ჩუმად ვარ, თან ეცადე არ გამოიყენო ის -13dp

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/layout_receive_message.xml
> +        android:layout_marginTop="-5dp"
same

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/layout_receive_message.xml
> +        android:layout_marginTop="-5dp"
same

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/layout/layout_send_message.xml
you know what's wrong

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/values-night/color.xml
> +    <color name="nero">#191919</color>
ამ სახელებით ვერავინ გაიგებს რა ქოლორია

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/values-night/color.xml
> +    <color name="F7CE7F">#F7CE7F</color>
ეგ საერთოდ :)

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/values/colors.xml
same

2023-04-21 10:47 UTC, iTarley commented on app/src/main/res/values/dimens.xml
ზრდის მიხედვით თუ დაალაგებ, უკეთესი იქნება

2023-04-21 10:56 UTC, AnaRusadze requested changes

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/shape_circle.xml
> +<?xml version="1.0" encoding="utf-8"?>
v24დან drawable-ს ფექეჯში გადმოიტანე რაც გაქვს.
და სახელში მიუთითე რისი წრეა

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable-v24/shape_stroke_background.xml
> +</shape>
shape, stroke, background სამი სხვადასხვა ტიპის drawable არის, ამიტომ ვერ მივხვდი ზუსტად რომელია სახელით

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_moon_background.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
აქაც, ან ic უნდა აირჩიო ან bkg პრეფიქსი

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_moon_icon.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
ic და icon ერთი და იგივეს ნიშნავს, შეგიძლია icon მოაშორო

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_moon_layer_list.xml
> +</selector>
ეს რისთვის დაგჭირდა, მარტო მარჯინებისთვის?

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_send_icon.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
იგივე: ic და icon

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_sun_background.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
იგივე: ic და background

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/ic_sun_icon.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
იგივე: ic და icon

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/drawable/shape_color_background.xml
> +<?xml version="1.0" encoding="utf-8"?>
დააკონკრეტე რისი შეიფია

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/layout-land/activity_main.xml
> +        android:paddingBottom="30dp" />
გაიტანე ზომები dimenის ფაილის რესურსში, ბევრია გამორჩენილი და გადახედე

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/layout-land/activity_main.xml
> +        android:background="@color/F7CE7F" />
ფერის სახელს ჰეშკოდს არ არქმევენ ხოლმე, მაგრამ ჯერ იყოს, დიზაინერისგან როცა გვექნება ფერების სახელები, მერე შეგიძლია დაარეფაქტორო

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/layout/layout_send_message.xml
> +
ცოტა უფრო აკადემიური აპლიკაცია რომ იყოს,  შეგიძლია გრძელი ტექსტის მაგალითად lorem ipsum ის ტექსტი გამოიყენოთ ხოლმე. და კოდი დააფორმატირე

2023-04-21 10:56 UTC, AnaRusadze commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_8_sp">8sp</dimen>
დაალაგე ზრდადობით

2023-04-21 11:18 UTC, giorgimurgulia-space commented on app/src/main/java/com/insurance/chatapp/BottomUserFragment.kt
გთხოვთ მხოლოდ დიზაინი შემიფასოთ ამ ბრენჩზე, ფრაგმენტი მხოლოდ ტესტირებისთვის მაქვს აქ.

2023-04-21 11:31 UTC, giorgimurgulia-space commented on app/src/main/res/values-night/color.xml
> +    <color name="nero">#191919</color>
ფერის სახელია, როგორც მოიწერა ანამ ველოდებით დიზაინერისგან ფერების სახელებს.

2023-04-27 12:22 UTC, AnaRusadze commented on app/src/main/res/drawable/moon_bkg.xml
> +</vector>
bkg_moon უფრო სწორია

2023-04-27 12:22 UTC, AnaRusadze commented on app/src/main/res/drawable/sun_bck.xml
> +</vector>
bkg_sun

2023-04-27 12:22 UTC, AnaRusadze commented on app/src/main/res/layout-land/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
main activitty-ს გადაარქვი სახელი

2023-04-27 12:28 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/moon_bkg.xml
> +</vector>
done

2023-04-27 12:28 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/sun_bck.xml
> +</vector>
done

2023-04-27 12:28 UTC, giorgimurgulia-space commented on app/src/main/res/layout-land/activity_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2023-04-27 12:29 UTC, AnaRusadze commented on app/src/main/res/drawable/bck_sun.xml
> +</vector>
bkg

2023-04-27 12:31 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/bck_sun.xml
> +</vector>
done

2023-04-27 12:32 UTC, AnaRusadze approved these changes

2023-04-27 12:33 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/ic_moon_icon.xml
done

2023-04-27 12:33 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/ic_send_icon.xml
done

2023-04-27 12:33 UTC, giorgimurgulia-space commented on app/src/main/res/layout/layout_send_message.xml
done

2023-04-27 12:33 UTC, giorgimurgulia-space commented on app/src/main/res/values-night/color.xml
> +    <color name="F7CE7F">#F7CE7F</color>
done

2023-04-27 12:33 UTC, giorgimurgulia-space commented on app/src/main/res/values/dimens.xml
done

2023-04-27 12:38 UTC, ninikokra approved these changes

2023-04-27 13:13 UTC, bchmsl requested changes

2023-04-27 13:13 UTC, bchmsl commented on app/src/main/res/drawable/ic_moon_layer_list.xml
> +                android:top="3dp"
დიმენებში გაიტანე

2023-04-27 13:13 UTC, bchmsl commented on app/src/main/res/drawable/ic_sun_layer_list.xml
> +                android:top="3dp"
დიმენებში

2023-04-27 13:13 UTC, bchmsl commented on app/src/main/res/layout/fragment_bottom_user.xml
> +    <LinearLayout
თუ მოერიდები კონტეინერში კონტეინერის ჩაშენებას უმჯობესია, მატერიალით შეგიძლია გააკეთო უკეთესად

2023-04-27 13:17 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/ic_sun_layer_list.xml
> +                android:top="3dp"
done

2023-04-27 13:17 UTC, giorgimurgulia-space commented on app/src/main/res/drawable/ic_moon_layer_list.xml
> +                android:top="3dp"
done

2023-04-27 13:18 UTC, giorgimurgulia-space commented on app/src/main/res/layout/fragment_bottom_user.xml
> +    <LinearLayout
სტროუკისთვის მაქ ჩსმული ესე კარგად ჩაჯდა, სავარაუდოდ ერთ ფრაგმენტზე რო აგდავკეთებ ევცდები შევცვალო

2023-04-27 13:20 UTC, bchmsl approved these changes

2023-04-27 14:32 UTC, merged